Version: 1.0

Logging:
    Verbose: True

General:
    SqrtsNN: 2760.0
    Nucleus1:
        A:    208
        Z:    82
        mode: 0
    Nucleus2:
        A:    208
        Z:    82
        mode: 0
    GlauberAcceptance: Gaussian
    Events: 10
    Model: 0
    Impact:
        Value: 2.5
    PDFs:
      PDFSet: CT18NNLO
      ForcePositive: 1
    K-Factor: 1.

Grid:
    NX:        241
    NY:        241
    NETA:      101
    X_RANGE:   [-12,12]
    Y_RANGE:   [-12,12]
    ETA_RANGE: [-10,10]
    BG: 0.156

Model_Parameters:
    Q02:    0.152
    x0:     1
    lambda: 0.215
    XCut:  1.0

Output:
    path_to_output: Runs/
    run_name: PbPb_2760GeV_GBW
    Format: ["EMoments","NMoments","Charges"]
