Version:1.0

Logging:
    Verbose: True

General:
    SqrtsNN: 2760
    Nucleus1:
        A: 208
        Z: 82
        mode: 0
    Nucleus2:
        A: 208
        Z: 82
        mode: 0
    Events: 10
    Model: 1
    Impact:
        Range:  [0,40]
        Sampling:  Quadratic
    Seed: 2020298335
    PDFs: 
        PDFSet: CT18NNLO
        ForcePositive: 1
    K-Factor: 1

Grid:
    NX: 241
    NY: 241
    NETA: 101
    X_RANGE: [-12,12]
    Y_RANGE: [-12,12]
    ETA_RANGE: [-10,10]
    BG: 0.156

Model_Parameters:
    Set: 1
    XScaling: 0.01
    P_reg: 0

Output:
    path_to_output: Runs
    Format:  ["EMoments", "NMoments", "Charges"]

